### ISSUE TITLE
No longer works with Sketch 45

### ISSUE THREAD

**Issue by craigmdennis** [ErikFontanel/sketch-toggle-constrain-proportions#3]
There may have been some breaking changes.

**Comment by ErikFontanel** [comment]
Thanks for the heads up! I've seen multiple plugins break since 45 due different undocumented API changes. Fortunately this is a very small plugin so it should be easy to fix. Hold on for now!

**Comment by ErikFontanel** [comment]
Fixed it, please download the [latest release](https://github.com/ErikFontanel/sketch-toggle-constrain-proportions/releases/latest)
