### ISSUE TITLE
No longer works in Sketch 49

### ISSUE THREAD

**Issue by craigmdennis** [ErikFontanel/sketch-toggle-constrain-proportions#5]
There may have been some breaking changes similar to #3

**Comment by ErikFontanel** [comment]
here we go again… though with the new API in Sketch 49 it shouldn't be too much of a problem I guess 🤞

**Comment by ErikFontanel** [comment]
hi @craigmdennis I've solved the compatibility issue. But I couldn't get the lock icon to update after the constrains are toggled. So I released a prerelease, you can find it here:
https://github.com/ErikFontanel/sketch-toggle-constrain-proportions/releases/tag/v1.2.1-0

If I'm able to resolve the UI update than I'll do a full release.

**Comment by ErikFontanel** [comment]
@craigmdennis I've resolved the UI issue too and released v1.2.1, you can download it from the [releases page](https://github.com/ErikFontanel/sketch-toggle-constrain-proportions/releases) or through the Sketch updater.
